---
title: "Lab 03 - Nobel laureates"
author: "Yang"
date: "2024.03.10"
output: github_document
---

### Load packages and data

```{r load-packages, message=FALSE}
library(tidyverse) 
```

```{r load-data, message=FALSE}
nobel <- read_csv("data/nobel.csv")
```

## Exercises

### Exercise 1
```{r exercise-1}
nrow(nobel)
ncol(nobel)

```

### Exercise 2

```{r exercise-2}
library(tidyverse)
nobel_living <- nobel %>% 
  filter(is.na(died_date),
         !is.na(country),
         gender !="org")

#write.csv(nobel_living, "nobel_living2.csv", row.names = FALSE) 

```
you are left with a data frame with `r nrow(nobel_living)` observations.

```{r create-nobel-living-science}
library(dplyr)
library(tidyverse)
nobel_living<-nobel_living %>% 
  mutate(country_us = if_else(country == "USA","USA","other"))
nobel_living_science<-nobel_living %>% 
  filter(category %in% c("Physics", "Medicine", "Chemistry", "Economics"))
  
  
```
### Exercise 3

```{r exercise-3}

# 创建分面柱状图
# 使用ggplot2创建可视化
ggplot(nobel_living_science, aes(x = category, fill = country_us)) +
  geom_bar(position = "dodge") + # 使用"dodge"位置调整来并排显示条形
  facet_wrap(~ category) + # 按类别分面
  coord_flip() + # 翻转坐标，使条形呈水平方向
  labs(title = "Nobel Prize Laureates by Category and Country",
       x = "Category",
       y = "Count",
       fill = "Laureate Location") +
  theme_minimal()

  
  
```
### Exercise 4

...

### Exercise 5

...

### Exercise 6

...
